import React, { createContext, useState, useContext, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'es' | 'ru' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.affirmations': 'Soul Compass',
    'nav.gita': 'Bhagavad Gita',
    'nav.geet': 'Vaishnav Geet',
    'nav.temples': 'Temples',
    'nav.news': 'News',
    'nav.pilgrimage': 'Pilgrimage & History',
    'footer.slogan': 'Chant Hare Krishna and be happy.',
    'footer.rights': 'ISKCON Devotee Community. All rights reserved.',
    'home.hero.title': 'Hare Krishna',
    'home.hero.subtitle': 'Discover the wisdom of the Bhagavad Gita, find peace in Vaishnav melodies, and connect with your spiritual community.',
    'home.cta.read': 'Read Bhagavad Gita',
    'home.cta.find': 'Find a Temple',
    'home.card.wisdom': 'Daily Wisdom',
    'home.card.wisdom.desc': 'Read daily verses from the Bhagavad Gita As It Is with purports by Srila Prabhupada.',
    'home.card.music': 'Devotional Music',
    'home.card.music.desc': 'Listen to and learn the lyrics of beautiful Vaishnav bhajans and kirtans.',
    'home.card.community': 'Community',
    'home.card.community.desc': 'Stay updated with global news, festivals, and find temples near you.',
    'gita.title': 'Bhagavad Gita As It Is',
    'gita.author': 'By His Divine Grace A.C. Bhaktivedanta Swami Prabhupada',
    'gita.chapter': 'Chapter',
    'gita.verse': 'Verse',
    'gita.readBtn': 'Read Verse',
    'gita.reading': 'Reading...',
    'gita.selectChapter': 'Select a chapter...',
    'geet.title': 'Vaishnav Geet',
    'geet.subtitle': 'Immerse yourself in the transcendental vibration of devotional songs.',
    'geet.popular': 'Popular Bhajans',
    'geet.select': 'Select a Bhajan',
    'geet.select.desc': 'Choose a song from the list to view lyrics and translation.',
    'geet.cat.all': 'All Songs',
    'geet.cat.aarti': 'Aartis & Pranam',
    'geet.cat.goswami': 'Six Goswamis',
    'geet.cat.acharyas': 'Vaishnava Acharyas',
    'temples.title': 'Temple Locator',
    'temples.subtitle': 'Find your nearest ISKCON center and connect with the community.',
    'temples.placeholder': 'Enter city, state, or country',
    'temples.nearMe': 'Near Me',
    'temples.search': 'Search',
    'temples.searching': 'Searching...',
    'news.title': 'Community News',
    'news.subtitle': 'Latest updates from the ISKCON community.',
    'news.official': 'Official Channels',
    'news.upcoming': 'Upcoming Events',
    'news.latest': 'Latest Updates',
    'news.location': 'Detecting location...',
    'news.global': 'Showing Global News',
    'news.local': 'News for your location',
    'pilgrim.title': 'Braj Mandal & Goswamis',
    'pilgrim.subtitle': 'Explore the lives of the Six Goswamis and the holy places of Braj Bhumi.',
    'pilgrim.tab.saints': 'Saints & Goswamis',
    'pilgrim.tab.places': 'Holy Places',
    'pilgrim.tab.temples': 'Goswami Temples',
    'pilgrim.select': 'Select an item to view details',
  },
  hi: {
    'nav.home': 'मुख्य पृष्ठ',
    'nav.affirmations': 'आत्म दिशा',
    'nav.gita': 'भगवद गीता',
    'nav.geet': 'वैष्णव गीत',
    'nav.temples': 'मंदिर',
    'nav.news': 'समाचार',
    'nav.pilgrimage': 'तीर्थ और इतिहास',
    'footer.slogan': 'हरे कृष्ण महामंत्र का जाप करें और खुश रहें।',
    'footer.rights': 'इस्कॉन भक्त समुदाय। सर्वाधिकार सुरक्षित।',
    'home.hero.title': 'हरे कृष्ण',
    'home.hero.subtitle': 'भगवद गीता के ज्ञान की खोज करें, वैष्णव धुनों में शांति पाएं और अपने आध्यात्मिक समुदाय से जुड़ें।',
    'home.cta.read': 'भगवद गीता पढ़ें',
    'home.cta.find': 'मंदिर खोजें',
    'home.card.wisdom': 'दैनिक ज्ञान',
    'home.card.wisdom.desc': 'श्रीला प्रभुपाद के तात्पर्य के साथ भगवद गीता यथारूप के दैनिक श्लोक पढ़ें।',
    'home.card.music': 'भक्ति संगीत',
    'home.card.music.desc': 'सुंदर वैष्णव भजनों और कीर्तनों को सुनें और उनके बोल सीखें।',
    'home.card.community': 'समुदाय',
    'home.card.community.desc': 'वैश्विक समाचार, त्योहारों के साथ अपडेट रहें और अपने पास के मंदिर खोजें।',
    'gita.title': 'भगवद गीता यथारूप',
    'gita.author': 'कृष्णकृपामूर्ति श्री श्रीमद् ए.सी. भक्तिवेदांत स्वामी प्रभुपाद द्वारा',
    'gita.chapter': 'अध्याय',
    'gita.verse': 'श्लोक',
    'gita.readBtn': 'श्लोक पढ़ें',
    'gita.reading': 'पढ़ रहे हैं...',
    'gita.selectChapter': 'एक अध्याय चुनें...',
    'geet.title': 'वैष्णव गीत',
    'geet.subtitle': 'भक्ति गीतों के दिव्य स्पंदन में डूब जाएं।',
    'geet.popular': 'लोकप्रिय भजन',
    'geet.select': 'एक भजन चुनें',
    'geet.select.desc': 'गीत और अनुवाद देखने के लिए सूची से एक गीत चुनें।',
    'geet.cat.all': 'सभी गीत',
    'geet.cat.aarti': 'आरती और प्रणाम',
    'geet.cat.goswami': 'षड गोस्वामी',
    'geet.cat.acharyas': 'वैष्णव आचार्य',
    'temples.title': 'मंदिर लोकेटर',
    'temples.subtitle': 'अपने निकटतम इस्कॉन केंद्र को खोजें और समुदाय से जुड़ें।',
    'temples.placeholder': 'शहर, राज्य या देश दर्ज करें',
    'temples.nearMe': 'मेरे पास',
    'temples.search': 'खोजें',
    'temples.searching': 'खोज रहे हैं...',
    'news.title': 'सामुदायिक समाचार',
    'news.subtitle': 'इस्कॉन समुदाय से नवीनतम अपडेट।',
    'news.official': 'आधिकारिक चैनल',
    'news.upcoming': 'आगामी कार्यक्रम',
    'news.latest': 'नवीनतम अपडेट',
    'news.location': 'स्थान का पता लगाया जा रहा है...',
    'news.global': 'वैश्विक समाचार दिखाया जा रहा है',
    'news.local': 'आपके स्थान के लिए समाचार',
    'pilgrim.title': 'ब्रज मंडल और गोस्वामी',
    'pilgrim.subtitle': 'षड गोस्वामियों के जीवन और ब्रज भूमि के पवित्र स्थानों का अन्वेषण करें।',
    'pilgrim.tab.saints': 'संत और गोस्वामी',
    'pilgrim.tab.places': 'पवित्र स्थान',
    'pilgrim.tab.temples': 'गोस्वामी मंदिर',
    'pilgrim.select': 'विवरण देखने के लिए एक आइटम चुनें',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.affirmations': 'Brújula del Alma',
    'nav.gita': 'Bhagavad Gita',
    'nav.geet': 'Vaishnav Geet',
    'nav.temples': 'Templos',
    'nav.news': 'Noticias',
    'nav.pilgrimage': 'Peregrinaje e Historia',
    'footer.slogan': 'Canta Hare Krishna y sé feliz.',
    'footer.rights': 'Comunidad de Devotos de ISKCON. Todos los derechos reservados.',
    'home.hero.title': 'Hare Krishna',
    'home.hero.subtitle': 'Descubre la sabiduría del Bhagavad Gita, encuentra paz en las melodías Vaishnavas y conéctate con tu comunidad espiritual.',
    'home.cta.read': 'Leer Bhagavad Gita',
    'home.cta.find': 'Buscar Templo',
    'home.card.wisdom': 'Sabiduría Diaria',
    'home.card.wisdom.desc': 'Lee versos diarios del Bhagavad Gita Tal Como Es con significados de Srila Prabhupada.',
    'home.card.music': 'Música Devocional',
    'home.card.music.desc': 'Escucha y aprende la letra de hermosos bhajans y kirtans Vaishnavas.',
    'home.card.community': 'Comunidad',
    'home.card.community.desc': 'Mantente actualizado con noticias globales, festivales y encuentra templos cerca de ti.',
    'gita.title': 'Bhagavad Gita Tal Como Es',
    'gita.author': 'Por Su Divina Gracia A.C. Bhaktivedanta Swami Prabhupada',
    'gita.chapter': 'Capítulo',
    'gita.verse': 'Verso',
    'gita.readBtn': 'Leer Verso',
    'gita.reading': 'Leyendo...',
    'gita.selectChapter': 'Selecciona un capítulo...',
    'geet.title': 'Vaishnav Geet',
    'geet.subtitle': 'Sumérgete en la vibración trascendental de las canciones devocionales.',
    'geet.popular': 'Bhajans Populares',
    'geet.select': 'Selecciona un Bhajan',
    'geet.select.desc': 'Elige una canción de la lista para ver la letra y la traducción.',
    'geet.cat.all': 'Todas las Canciones',
    'geet.cat.aarti': 'Aartis y Pranam',
    'geet.cat.goswami': 'Seis Goswamis',
    'geet.cat.acharyas': 'Acharyas Vaishnavas',
    'temples.title': 'Localizador de Templos',
    'temples.subtitle': 'Encuentra tu centro ISKCON más cercano y conéctate con la comunidad.',
    'temples.placeholder': 'Ingresa ciudad, estado o país',
    'temples.nearMe': 'Cerca de Mí',
    'temples.search': 'Buscar',
    'temples.searching': 'Buscando...',
    'news.title': 'Noticias de la Comunidad',
    'news.subtitle': 'Últimas actualizaciones de la comunidad ISKCON.',
    'news.official': 'Canales Oficiales',
    'news.upcoming': 'Próximos Eventos',
    'news.latest': 'Últimas Actualizaciones',
    'news.location': 'Detectando ubicación...',
    'news.global': 'Mostrando noticias globales',
    'news.local': 'Noticias para tu ubicación',
    'pilgrim.title': 'Braj Mandal y Goswamis',
    'pilgrim.subtitle': 'Explora las vidas de los Seis Goswamis y los lugares sagrados de Braj Bhumi.',
    'pilgrim.tab.saints': 'Santos y Goswamis',
    'pilgrim.tab.places': 'Lugares Sagrados',
    'pilgrim.tab.temples': 'Templos de Goswamis',
    'pilgrim.select': 'Seleccione un elemento para ver los detalles',
  },
  ru: {
    'nav.home': 'Главная',
    'nav.affirmations': 'Компас Души',
    'nav.gita': 'Бхагавад-гита',
    'nav.geet': 'Вайшнавские песни',
    'nav.temples': 'Храмы',
    'nav.news': 'Новости',
    'nav.pilgrimage': 'Паломничество',
    'footer.slogan': 'Пойте Харе Кришна и будьте счастливы.',
    'footer.rights': 'Сообщество преданных ИСККОН. Все права защищены.',
    'home.hero.title': 'Харе Кришна',
    'home.hero.subtitle': 'Откройте для себя мудрость Бхагавад-гиты, обретите покой в вайшнавских мелодиях и общайтесь с духовным сообществом.',
    'home.cta.read': 'Читать Бхагавад-гиту',
    'home.cta.find': 'Найти храм',
    'home.card.wisdom': 'Ежедневная мудрость',
    'home.card.wisdom.desc': 'Читайте ежедневные стихи из Бхагавад-гиты как она есть с комментариями Шрилы Прабхупады.',
    'home.card.music': 'Духовная музыка',
    'home.card.music.desc': 'Слушайте и изучайте тексты прекрасных вайшнавских бхаджанов и киртанов.',
    'home.card.community': 'Сообщество',
    'home.card.community.desc': 'Будьте в курсе мировых новостей, фестивалей и находите храмы рядом с вами.',
    'gita.title': 'Бхагавад-гита как она есть',
    'gita.author': 'Его Божественная Милость А.Ч. Бхактиведанта Свами Прабхупада',
    'gita.chapter': 'Глава',
    'gita.verse': 'Стих',
    'gita.readBtn': 'Читать стих',
    'gita.reading': 'Загрузка...',
    'gita.selectChapter': 'Выберите главу...',
    'geet.title': 'Вайшнавские песни',
    'geet.subtitle': 'Погрузитесь в трансцендентную вибрацию молитвенных песен.',
    'geet.popular': 'Популярные бхаджаны',
    'geet.select': 'Выберите бхаджан',
    'geet.select.desc': 'Выберите песню из списка, чтобы просмотреть текст и перевод.',
    'geet.cat.all': 'Все песни',
    'geet.cat.aarti': 'Арати и Пранам',
    'geet.cat.goswami': 'Шесть Госвами',
    'geet.cat.acharyas': 'Вайшнавские Ачарьи',
    'temples.title': 'Поиск храмов',
    'temples.subtitle': 'Найдите ближайший центр ИСККОН и присоединитесь к сообществу.',
    'temples.placeholder': 'Введите город, штат или страну',
    'temples.nearMe': 'Рядом со мной',
    'temples.search': 'Поиск',
    'temples.searching': 'Поиск...',
    'news.title': 'Новости сообщества',
    'news.subtitle': 'Последние новости сообщества ИСККОН.',
    'news.official': 'Официальные каналы',
    'news.upcoming': 'Предстоящие события',
    'news.latest': 'Последние обновления',
    'news.location': 'Определение местоположения...',
    'news.global': 'Показаны мировые новости',
    'news.local': 'Новости для вашего местоположения',
    'pilgrim.title': 'Врадж Мандал и Госвами',
    'pilgrim.subtitle': 'Изучите жизнь Шести Госвами и святые места Врадж Бхуми.',
    'pilgrim.tab.saints': 'Святые и Госвами',
    'pilgrim.tab.places': 'Святые места',
    'pilgrim.tab.temples': 'Храмы Госвами',
    'pilgrim.select': 'Выберите элемент для просмотра подробностей',
  },
  bn: {
    'nav.home': 'হোম',
    'nav.affirmations': 'আত্ম দিশা',
    'nav.gita': 'ভগবদ্গীতা',
    'nav.geet': 'বৈষ্ণব গীত',
    'nav.temples': 'মন্দির',
    'nav.news': 'সংবাদ',
    'nav.pilgrimage': 'তীর্থ ও ইতিহাস',
    'footer.slogan': 'হরে কৃষ্ণ মহামন্ত্র জপ করুন এবং সুখী হন।',
    'footer.rights': 'ইসকন ভক্ত সমাজ। সর্বস্বত্ব সংরক্ষিত।',
    'home.hero.title': 'হরে কৃষ্ণ',
    'home.hero.subtitle': 'ভগবদ্গীতার জ্ঞান আবিষ্কার করুন, বৈষ্ণব সুরে শান্তি পান এবং আপনার আধ্যাত্মিক সমাজের সাথে যুক্ত হন।',
    'home.cta.read': 'ভগবদ্গীতা পড়ুন',
    'home.cta.find': 'মন্দির খুঁজুন',
    'home.card.wisdom': 'দৈনিক জ্ঞান',
    'home.card.wisdom.desc': 'শ্রীল প্রভুপাদের তাৎপর্য সহ ভগবদ্গীতা যথার্থর দৈনিক শ্লোক পড়ুন।',
    'home.card.music': 'ভক্তি সঙ্গীত',
    'home.card.music.desc': 'সুন্দর বৈষ্ণব ভজন এবং কীর্তন শুনুন এবং লিরিক্স শিখুন।',
    'home.card.community': 'সম্প্রদায়',
    'home.card.community.desc': 'বিশ্ব সংবাদ, উৎসব এবং আপনার নিকটবর্তী মন্দির সম্পর্কে আপডেট থাকুন।',
    'gita.title': 'ভগবদ্গীতা যথার্থ',
    'gita.author': 'কৃষ্ণকৃপাশ্রীমূর্তি শ্রীল অভয়চরণারবিন্দ ভক্তিবেদান্ত স্বামী প্রভুপাদ',
    'gita.chapter': 'অধ্যায়',
    'gita.verse': 'শ্লোক',
    'gita.readBtn': 'শ্লোক পড়ুন',
    'gita.reading': 'পড়া হচ্ছে...',
    'gita.selectChapter': 'একটি অধ্যায় নির্বাচন করুন...',
    'geet.title': 'বৈষ্ণব গীত',
    'geet.subtitle': 'ভক্তি গানের অপ্রাকৃত স্পন্দনে নিজেকে নিমজ্জিত করুন।',
    'geet.popular': 'জনপ্রিয় ভজন',
    'geet.select': 'একটি ভজন নির্বাচন করুন',
    'geet.select.desc': 'লিরিক্স এবং অনুবাদ দেখতে তালিকা থেকে একটি গান বেছে নিন।',
    'geet.cat.all': 'সমস্ত গান',
    'geet.cat.aarti': 'আরতি ও প্রণাম',
    'geet.cat.goswami': 'ষড় গোস্বামী',
    'geet.cat.acharyas': 'বৈষ্ণব আচার্য',
    'temples.title': 'মন্দির লোকেটার',
    'temples.subtitle': 'আপনার নিকটতম ইসকন কেন্দ্র খুঁজুন এবং সম্প্রদায়ের সাথে যুক্ত হন।',
    'temples.placeholder': 'শহর, রাজ্য বা দেশ লিখুন',
    'temples.nearMe': 'আমার কাছাকাছি',
    'temples.search': 'অনুসন্ধান',
    'temples.searching': 'অনুসন্ধান করা হচ্ছে...',
    'news.title': 'সম্প্রদায়ের খবর',
    'news.subtitle': 'ইসকন সম্প্রদায়ের সর্বশেষ আপডেট।',
    'news.official': 'অফিসিয়াল চ্যানেল',
    'news.upcoming': 'আসন্ন ইভেন্ট',
    'news.latest': 'সর্বশেষ আপডেট',
    'news.location': 'অবস্থান সনাক্ত করা হচ্ছে...',
    'news.global': 'বিশ্ব সংবাদ দেখানো হচ্ছে',
    'news.local': 'আপনার অবস্থানের জন্য খবর',
    'pilgrim.title': 'ব্রজ মন্ডল ও গোস্বামী',
    'pilgrim.subtitle': 'ষড় গোস্বামীদের জীবন এবং ব্রজ ভূমির পবিত্র স্থানগুলি অন্বেষণ করুন।',
    'pilgrim.tab.saints': 'সাধু ও গোস্বামী',
    'pilgrim.tab.places': 'পবিত্র স্থান',
    'pilgrim.tab.temples': 'গোस्वामी মন্দির',
    'pilgrim.select': 'বিস্তারিত দেখতে একটি আইটেম নির্বাচন করুন',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};